CC=gcc
SOURCES=controller.c cost.c worker.c functions.h hardwareAPI.c hardwareAPI.h
CFLAGS=-Wall -pthread -g
OUTPUT=-o a.out
LIBS =

all:
	    $(CC) $(SOURCES) $(OUTPUT) $(CFLAGS) $(LIBS)

clean:
	    rm -f a.out *.o
